In [1]:
import pandas as pd

In [40]:
pd_df = pd.read_csv('/PD 2021 Wk 1 Input - Bike Sales.csv')

In [41]:
## Split Store and Bike into new columns
pd_df[['Store', 'Bike']] = pd_df['Store - Bike'].str.split(' - ', expand=True)

In [42]:
## Name Correction
name_correction_dict = {'R': 'Road', 'M': 'Mountain', 'G': 'Gravel'}

pd_df['Bike'] = pd_df['Bike'].apply(lambda x: name_correction_dict.get(x[0], 'Other'))

In [43]:
## Convert date to date
pd_df['Date'] = pd.to_datetime(df['Date'])

## Create Quarter
pd_df['Quarter'] = pd_df['Date'].dt.quarter

## Create Day of Month
pd_df['Day_of_Month'] = pd_df['Date'].dt.day

<ipython-input-43-1a9ef0463949>:2: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  pd_df['Date'] = pd.to_datetime(df['Date'])

In [44]:
## Obtain first 10 rows
pd_df = pd_df[pd_df['Order ID'] > 10]

In [47]:
## Remove unwanted columns
pd_df = pd_df.drop(['Date' ,'Store - Bike'], axis=1)

In [48]:
pd_df

,Order ID,Customer Age,Bike Value,Existing Customer?,Store,Bike,Quarter,Day_of_Month
10,11,57,902,No,Birmingham,Road,4,4
11,12,31,946,Yes,Leeds,Road,1,17
12,13,17,1296,Yes,Birmingham,Road,4,25
13,14,59,1166,Yes,Manchester,Road,3,18
14,15,24,1781,No,Manchester,Mountain,4,10
...,...,...,...,...,...,...,...,...
995,996,42,3460,No,London,Mountain,3,3
996,997,48,3409,No,London,Mountain,1,17
997,998,81,2534,No,London,Mountain,1,26
998,999,37,4312,Yes,London,Gravel,2,25
999,1000,35,1200,Yes,Leeds,Gravel,1,18